feature/update i18n to model v3
robert-koch-institut/mex-model pull request #111
Opened 2024-08-23 13:13 UTC by LeipoldL

# Changes
- new metadata fields in german included

# Removed
- outdated metadata fields removed

2024-08-23 13:16 UTC, LeipoldL commented
1.	PR
2.	Metadatenfelder
Ich habe überprüft ob alle Metadatenfelder in dem i18n File beschrieben werden. Alle fehlenden Felder habe ich ergänzt und Definitionen dafür erstellt. Inzwischen überholte Felder habe ich gelöscht.
Folgende Metadatenfelder habe ich außen vorgelassen. Bitte nochmal prüfen, ob das so korrekt ist oder wir zu manchen doch noch Bezeichnungen brauchen, da wir innerhalb des Wireframes auch auf die Verknüpfung zu z.B. zugehörigen Forschungsdaten hinweisen etc:
•	alternateIdentifier
•	belongsTo
•	containedBy
•	distribution
•	hadPrimarySource
•	identifier
•	identifierInPrimarySource
•	isPartOf
•	isPartOfActivity
•	stableTargetId
•	usedIn
•	wasGeneratedBy
3.	Singular / Plural
Ich war unsicher, woher bekannt ist, ob Einzahl/Mehrzahl beschrieben sein muss. Bitte im Zweifel gerne ergänzen oder löschen.
4.	Unterscheidung nach Entität
Bei manchen Metadatenfeldern war eine Unterscheidung nach Entitäten vorgenommen z.B. bei AccessRestriction
msgid "accessRestriction.singular"
msgstr "Zugriffsbeschränkung"

msgid "accessRestriction.description"
msgstr ""
"Beschreibung der Zugangsbeschränkung"

msgctxt "BibliographicResource"
msgid "accessRestriction.description"
msgstr "Beschreibung, ob die Publikation für alle zugänglich ist (offen) oder einen"
" eingeschränkten Zugang hat (restriktiv)"

msgctxt "Distribution"
msgid "accessRestriction.description"
msgstr "Beschreibung, ob die Forschungsdaten für alle zugänglich sind (offen) oder einen"
" eingeschränkten Zugang haben (restriktiv)"

msgctxt "Resource"
msgid "accessRestriction.description"
msgstr "Beschreibung, ob die Forschungsdaten für alle zugänglich sind (offen) oder einen"
" eingeschränkten Zugang haben (restriktiv)"
Bei anderen Feldern wie „title“ war hingegen keine Unterscheidung vorgenommen, obwohl das Metadatenfeld in mehreren Entitäten vorkommt. Ich konnte hier kein durchgängiges Muster erkennen, wann das erfolgt und wann nicht.

5.	Ressource
Ich habe in sämtlichen Texten den Begriff „Daten“ und „Ressource“ durch Forschungsdaten ersetzt. Unser Plan war ja auch in der neuen Suchmaschine nicht von Ressourcen zu sprechen, weil das immer für alle zu verwirrend war, sondern den Begriff Forschungsdaten zu verwenden
6.	Modell Update
Der Entität „BibliographicResource“ ist inzwischen zwar das abhanden gekommene Feld „placePublished“ hinzugefügt worden; allerdings hatten wir uns hier eigtl. auf die Benennung PublicationPlace geeinigt, damit es konform mit PublicationYear ist. Ist das noch möglich zu ändern? Falls ja, dann müsste es in diesem File dann auch aktualisiert werden. 
7.	UserInterface
Ich habe die Beschreibung für „timePeriod“ erhalten, weil wir ja im UserInterface dann eine Verknüpfung aus den Felder start und end nehmen um den Zeitraum abzubilden. Ist das korrekt?

Falls ja, bräuchten wir dann hier noch weitere Beschreibungen für kombinierte Felder, wie z.B. ResourceTypeGeneric und ResourceTypeSpecific. Hier müssten wir dann nochmal analysieren, welche zusammengesetzten weiteren Felder wir bräuchten, wenn das hier an dieser Stelle abgebildet wird. 
8.	I18n File
Ich habe jetzt zunächst erstmal die Änderungen in der deutschen Fassung vorgenommen. Erst wenn diese steht, sollten wir dann analog dazu die englische Fassung erstellen.

2024-09-05 12:46 UTC, fdiehr commented
> Bei anderen Feldern wie „title“ war hingegen keine Unterscheidung vorgenommen, obwohl das Metadatenfeld in mehreren Entitäten vorkommt. Ich konnte hier kein durchgängiges Muster erkennen, wann das erfolgt und wann nicht.

Ich glaube es kommt daher, dass wir für einige der Felder, die in mehreren Entitäten vorkommen, keine unterschiedlichen Anzeigetexte definiert haben, z. B. "Titel" ist immer "Titel", egal welcher Entitätentyp. Nur wenn der Anzeigetext spezifisch für ein Entitätentyp sein soll, muss das spezifiziert werden. Aber ob das stimmt, kann @cutoffthetop vielleicht bestätigen?

2024-09-05 13:16 UTC, fdiehr commented
> Folgende Metadatenfelder habe ich außen vorgelassen. Bitte nochmal prüfen, ob das so korrekt ist oder wir zu manchen doch noch Bezeichnungen brauchen, da wir innerhalb des Wireframes auch auf die Verknüpfung zu z.B. zugehörigen Forschungsdaten hinweisen etc:
• alternateIdentifier
• belongsTo
• containedBy
• distribution
• hadPrimarySource
• identifier
• identifierInPrimarySource
• isPartOf
• isPartOfActivity
• stableTargetId
• usedIn
• wasGeneratedBy

Die Übersetzungen werden auch für den MEx Editor benötigt, deswegen wäre es sinnvoll für alle Properties auch Übersetzungen zu haben. Ich pflege die gern nach.

2024-09-05 14:52 UTC, fdiehr commented
> Singular / Plural
> Ich war unsicher, woher bekannt ist, ob Einzahl/Mehrzahl beschrieben sein muss. Bitte im Zweifel gerne ergänzen oder löschen.

Das hängt davon ab, wie es im Modell definiert ist. Wenn die Property den `"type": "array"` hat, dann können da mehrere values sein, z. B. mehrere alternative Bezeichnungen. Ich gucke es nochmal durch und arbeite das nach.

2024-09-05 15:31 UTC, fdiehr requested changes

2024-09-06 11:30 UTC, LeipoldL commented on mex/model/i18n/de-DE.po
> +msgstr[1] "Projektarten"
Dann würde ich hierzu vorschlagen, dass wir dann auch in der Bezeichnung Projekttyp nutzen. Dann ist es allgemeiner. In der Erklärung sollten wir dann aber noch den Aspekt zur Finanzierung hinzufügen.

2024-09-06 11:38 UTC, LeipoldL commented on mex/model/i18n/de-DE.po
> +msgstr[0] "Projektart"
```suggestion
msgstr[0] "Projekttyp"
```

2024-09-06 11:38 UTC, LeipoldL commented on mex/model/i18n/de-DE.po
> +msgstr[1] "Projektarten"
```suggestion
msgstr[1] "Projekttypen"
```

2024-09-06 11:41 UTC, LeipoldL commented on mex/model/i18n/de-DE.po
> +msgstr "Typ des Projekts/Vorhabens"
```suggestion
msgstr "Der Typ des Projekts/Vorhabens gibt an, ob es sich um ein internes Projekt/Vorhaben oder ein drittmittelgefördertes Projekt handelt."
```

2024-09-06 11:44 UTC, LeipoldL reviewed
changes approved
added suggestion for open question

2024-09-06 11:58 UTC, fdiehr approved these changes

2024-09-13 11:31 UTC, cutoffthetop commented
> "Titel" ist immer "Titel", egal welcher Entitätentyp. Nur wenn der Anzeigetext spezifisch für ein Entitätentyp sein soll, muss das spezifiziert werden. Aber ob das stimmt, kann @cutoffthetop vielleicht bestätigen?

ja genau, das war der einzige Grund

2024-09-13 11:36 UTC, cutoffthetop commented
> Und vielleicht kann @cutoffthetop auch sagen, warum wir nicht das JSON Format verwenden? Oder hab ich hier die falsche Doku gefunden: https://www.i18next.com ? Generell finde ich die Dateien auch sehr unübersichtlich. Können wir z. B. die Reihenfolge ändern?

PO ist quasi die Großmutter der i18n Formate und die meisten modernen Tools können das entweder direkt lesen oder zumindest konvertieren.

> Generell finde ich die Dateien auch sehr unübersichtlich. Können wir z. B. die Reihenfolge ändern?

Am besten sind diese Files nicht manuell zu bearbeiten, sondern mit einem speziellen Editor.

2024-10-02 06:30 UTC, LeipoldL commented on mex/model/i18n/en-US.po
> +msgstr[1] "Contributing RKI untis"
units

2024-10-02 06:33 UTC, LeipoldL commented on mex/model/i18n/en-US.po
> +msgstr "Personenbezogene Daten"
Personal data

2024-10-02 06:39 UTC, LeipoldL commented on mex/model/i18n/en-US.po
> +msgctxt "Activity"                                                                                          # msgctxt "Activity" und "Variable" gibt es nicht mehr im Deutschen; zu entfernen
muss noch raus, siehe #

2024-10-02 06:39 UTC, LeipoldL commented on mex/model/i18n/en-US.po
> +msgid "keyword.description"                                                                                 # zu entfernen
muss noch raus, siehe #

2024-10-02 06:40 UTC, LeipoldL commented on mex/model/i18n/en-US.po
> +msgstr "Keywords describing the project"                                                                      # zu entfernen
muss noch raus, siehe #

2024-10-02 06:45 UTC, LeipoldL commented on mex/model/i18n/en-US.po
> +msgstr "Publication created within the scope of a research project/undertaking"
"/undertaking" löschen

2024-10-02 14:44 UTC, merged